### ISSUE TITLE
Check for Functions Throwing Errors

### ISSUE THREAD

**Issue by CIOData** [CARDS-Resources/CARDdealr#15]
Sean,
Is there a simple, automated function/process we could write to regularly test if any of these functions throw errors under basic usage so that we immediately know to address them? I'm thinking about two datasets in particular that have given me problems in the past: CDC Places and the EPA's EJScreen (which I'm about to write a function to pull). The problem with Places is that, if they update the dataset for some reason, they reissue a new API slug for it instead of overwriting the previous one. With EJScreen, they literally create a new folder in their file directory and rename the old folders the dumbest way imaginable (https://gaftp.epa.gov/EJScreen/2023/).

Thanks.

**Comment by seandavi** [comment]
The most natural answer is to write tests. The `testthat` package is most natural the way to go. For data, it can be a bit challenging to recognize all problems, but here is the approach I used for sars2pack:

- https://github.com/seandavi/sars2pack/blob/main/R/test_single_dataset.R
- https://github.com/seandavi/sars2pack/tree/main/tests/testthat

The "test" functions in the "tests" directory are generated automatically based on the data datalog. I can put that framework in place when I get a chance. I just haven't had time. 

I added an issue to track test framework creation. #18

**Comment by CIOData** [comment]
Sounds good. Yeah, my concern isn't as much about the data that gets pulled changing as it is just testing that the URL or API call works. The CDC has a bad habit of just disappearing the old links when they update a dataset instead of issuing the same link to the updated one.

**Comment by seandavi** [comment]
Testing will run the functions, so if they error, we'll catch it.

I'll close for now, but feel free to reopen.
